<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartAssistHub.Application\SmartAssistHub.Application.csproj" />
    <ProjectReference Include="..\SmartAssistHub.Infrastructure\SmartAssistHub.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartAssistHub.Persistence\SmartAssistHub.Persistence.csproj" />
  </ItemGroup>

</Project>
