<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartAssistHub.Application\SmartAssistHub.Application.csproj" />
    <ProjectReference Include="..\SmartAssistHub.Infrastructure\SmartAssistHub.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartAssistHub.Persistence\SmartAssistHub.Persistence.csproj" />
  </ItemGroup>

</Project>
